title: Nalia GK
logo: /assets/images/profile.png
description: Data Science Undergraduate | 2023 IISMA Awardee | Data Analyst & Machine Learning Enthusiast | Digital Illustrator 
show_downloads: true
theme: jekyll-theme-minimal
